scene:
  scene_path: "/PATH/TO/YOUR/OWN"
  dataset_name: "cocomap"
  test_cameras: False
  colmap_images: "images"
  colmap_eval_hold: 8
  downscale_ratio: 1
  white_background: False
  device: "cuda:0"
  
pipeline:
  convert_shs_python: False
  compute_cov3d_python: False
  debug: False
  seed: 1

model:
  sh_degree: 3
  model_dir: "/PATH/TO/YOUR/OWN"
  dynamic: False
  load_iteration: 10000
  device: "cuda:0"

fusion:
  out_dir: "/PATH/TO/YOUR/OWN"

distill:
  exp_name: openseg_new
  model_3d: MinkUNet34A
  voxel_size: 0.02
  aug: True
  feature_type: all
  lr: 0.001
  epochs: 100
  loss_type: cosine
  schedule_milestones: [20, 40, 60, 80, 100]
  schedule_gamma: 0.3
  batch_size: 1
  num_workers: 16
  test_interval: 10
  save_interval: 10
